### ISSUE TITLE
Bug report 3.4.2

### ISSUE THREAD

**Issue by DardBrinza** [walrusone/SkyWarsReloaded#60]
Latest paper 1.12.2
1) Click on spectator menu item
https://pastebin.com/qpCLSPp8

2) Error in code placeholders: {swr_kills} and {swr_losses}

3) {prefix} not displayed in chat section (messages.yml}

4) Add lighting if cage is a solid block (diamond block etc)

5) TPS drop https://timings.aikar.co/?id=eac36d95ff5d405a8f288955bbf3ab47#timings

6) Lag spike
http://dl3.joxi.net/drive/2018/03/25/0002/2579/178707/07/4c06c511a5.png
http://dl3.joxi.net/drive/2018/03/25/0002/2579/178707/07/56c3709b2f.png
http://dl3.joxi.net/drive/2018/03/25/0002/2579/178707/07/10a6125691.png

7) Where is access to kits through shop/level or how will default players get access to kits?

8) If server restart when the arena is running, sign is bugged and no longer works (sometimes randomly stop working).

9) Where translate {score} "(+7 Elo)" word?
http://dl3.joxi.net/drive/2018/03/26/0002/2579/178707/07/cca9335dc0.png

10) What is a scavenger chest? I did not find an application for it in the source code of the plugin, but it is in the voting menu.

11) {playercount} in waitstart messages not displayed

12) https://pastebin.com/uw7UAVuR

13) https://pastebin.com/U8rNHvet

14) https://pastebin.com/mnUKnUDe

15) https://pastebin.com/xUYCqftd

16) https://pastebin.com/jCX6FT3F

17) Is it possible to simplify the structure of the chests and KITs, as was done in old swr? I, like many, do everything through files, and not in the game and now it is very difficult and dreary.

18) Add the built-in game rules switch, I create an arena and there is an annotation of getting achievements under the standard and I have to edit the dat file of each arena to turn off the display of achievements in chat. (gamerule announceAchivements false)

19) Add to scoreboard -> playboard the number of players, how many players are alive, how many players are left.

20) Why is random join not the way it should be? I have 20+ maps, and players often fall almost on the same map.

21) The sign does not show maximum in game, but maximum in team (0/3)
http://dl3.joxi.net/drive/2018/04/14/0002/2579/178707/07/6be86794f2.png

**Comment by TheIntelloBox** [comment]
Me too.

**Comment by DardBrinza** [comment]
@walrusone

**Comment by walrusone** [comment]
The ones marked as fixed will be fixed in the next sync. Should be today or tomorrow, but it won't necessary go live on Spigot at that time. Updating to 1.13.2 is taking some time and testing.

1.	Should be fixed.
2.	Fixed
3.	I’ll add this to my todo list.
4.	Good idea, I’ll see what I can do.
5.	Sorry, couldn’t see timings roport anymore.
6.	I’ll look into these, but sometimes loading worlds can cause lag spikes. Not easily avoidable without switching to some kinda rollback system. I’m considering this, but we’ll see.
7.	This is covered in the plugin description on spigot.
8.	I’ve not been able to recreate this, but I’ll look into it and see if I can find something. 
9.	I never considered it actually. I’ll add it to todo list.
10.	Just empty chests. Players have to gather materials.
11.	This is something that got changed when I added parties. I’ll implement something soon to fix that.
12.	Fixed
13.	The pastebin never had the line reference for SkyWarsReloaded, but I think I have it fixed.
14.	Fixed
15.	Fixed
16.	Fixed
17.	The kit system I have created is much more versatile than the older yml types. It has a number of advantages that I don’t want to give up.
18.	I’ve added the announceAdvancements to false on map load for now. I may add a configurable system later.  
19.	I may add a option for this.
20.	I can make a toggle for this, but it’s meant to fill maps first (so that games start as fast as possible for the players) if it was completely random, then low player count may mean matches rarely starting.
21.	If it’s a teams map, it uses that format.
